name: CI

on:
  schedule:
    - cron: '0 0 * * *'
        
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
         curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
         postman login --with-api-key PMAK-65e214ca9fadee00019e2fcd-1c1fdf0ed2527f1f7c3e26ef080288d685
         postman collection run "https://github.com/ValeriaSpektor/hw_4.3.1/tree/ac02348acf51feba74dc8258b8815a3932bbd394/postman/collections" -e "postman_environment.json"
